//HintName: AutoInterfaceAttribute.g.cs
// This file was generated by Roozie.AutoInterface v1.0.0.0
using System;

namespace Roozie.AutoInterface;
#nullable enable

[AttributeUsage(AttributeTargets.Class, Inherited = false, AllowMultiple = false)]
internal sealed class AutoInterfaceAttribute : Attribute
{
    public AutoInterfaceAttribute()
    {
        GenerateAllMethods = true;
        GenerateAllProperties = true;
    }

    public AutoInterfaceAttribute(string? name, bool generateAllMethods = true, bool generateAllProperties = true)
    {
        Name = name;
        GenerateAllMethods = generateAllMethods;
        GenerateAllProperties = generateAllProperties;
    }

    public string? Name { get; set; }
    public bool GenerateAllMethods { get; set; } = true;
    public bool GenerateAllProperties { get; set; } = true;
}
