//HintName: ADifferentInterfaceName.g.cs
// <auto-generated>
// This file was generated by Roozie.AutoInterface v0.6.0.0
// </auto-generated>

using System;
using Roozie.AutoInterface;

namespace Roozie.AutoInterface.Tests;

#nullable enable

public partial interface ADifferentInterfaceName
{
    Guid Id { get; set; }

    string TestMethod(string input);
}
