//HintName: ADifferentInterfaceName.g.cs
// <auto-generated>
// This file was generated by Roozie.AutoInterface v0.4.0-beta
// </auto-generated>

using System;

namespace Roozie.AutoInterface.Tests;

#nullable enable

public partial interface ADifferentInterfaceName
{
    System.Guid Id {get;set;}

    string TestMethod(string input);
}
