//HintName: IAddToInterface_Attribute.g.cs
// This file was generated by Roozie.AutoInterface v0.1.0-beta
using Roozie.AutoInterface;
using System;
namespace Roozie.AutoInterface.Tests;
#nullable enable

public partial interface IAddToInterface_Attribute
{
    string? TestPropWithAttribute {get;set;}

    string? TestPropWithAttributePrivateSet {get;}

    string? TestPropWithAttributeInit {get;init;}

    int TestMethodWithAttribute(int input);
}
