//HintName: IAddToInterface_Attribute.g.cs
// <auto-generated>
// This file was generated by Roozie.AutoInterface v0.4.0-beta
// </auto-generated>

using System;

namespace Roozie.AutoInterface.Tests;

#nullable enable

public partial interface IAddToInterface_Attribute
{
    string? TestPropWithAttribute {get;set;}

    string TestPropWithAttributePrivateSet {get;}

    System.Guid? TestPropWithAttributeInit {get;init;}

    int TestMethodWithAttribute(int input);
}
