//HintName: IAddToInterface_Attribute.g.cs
// <auto-generated>
// This file was generated by Roozie.AutoInterface v0.6.1.0
// </auto-generated>

using System;
using Roozie.AutoInterface;

namespace Roozie.AutoInterface.Tests;

#nullable enable

public partial interface IAddToInterface_Attribute
{
    string? TestPropWithAttribute { get; set; }

    string TestPropWithAttributePrivateSet { get; }

    Guid? TestPropWithAttributeInit { get; init; }

    int TestMethodWithAttribute(int input);
}
