//HintName: ISimple.g.cs
// This file was generated by Roozie.AutoInterface v0.1.1-beta
using Roozie.AutoInterface;
using System;
using System.Text;
namespace Roozie.AutoInterface.Tests;
#nullable enable

public partial interface ISimple
{
    System.Guid Property {get;set;}

    int PropertyInit {get;init;}

    string? PropertyPrivateSet {get;}

    string TestMethod(string input);
}
