//HintName: AddToInterfaceAttribute.g.cs
// This file was generated by Roozie.AutoInterface v1.0.0.0
using System;

namespace Roozie.AutoInterface;
#nullable enable

[AttributeUsage(AttributeTargets.Method | AttributeTargets.Property, Inherited = false, AllowMultiple = false)]
internal sealed class AddToInterfaceAttribute : Attribute
{
}
