//HintName: IXmlDocComments.g.cs
// This file was generated by Roozie.AutoInterface v1.0.0.0
using Roozie.AutoInterface;
using System;
namespace Roozie.AutoInterface.Tests;
#nullable enable

/// <summary>
/// Test class
/// </summary>
/// <remarks>
/// Test class remarks
/// </remarks>
public partial interface IXmlDocComments
{
    /// <summary>
    /// Test property
    /// </summary>
    /// <remarks>
    /// Test property remarks
    /// </remarks>
    string? Test {get;}

    /// <summary>
    /// Test method <see cref="!:TestClass"/>
    /// </summary>
    /// <remarks>
    /// Test method remarks
    /// </remarks>
    /// <param name="input">Test input</param>
    /// <returns>Test output</returns>
    int TestMethod(int input);
}
