//HintName: AutoInterfaceAttribute.g.cs
// This file was generated by Roozie.AutoInterface v1.0.0.0
using System;

namespace Roozie.AutoInterface;
#nullable enable

[AttributeUsage(AttributeTargets.Class, Inherited = false, AllowMultiple = false)]
internal sealed class AutoInterfaceAttribute : Attribute
{
    public AutoInterfaceAttribute()
    {
        IncludeMethods = true;
        IncludeProperties = true;
    }

    public AutoInterfaceAttribute(string? name, bool includeMethods = true, bool includeProperties = true)
    {
        Name = name;
        IncludeMethods = includeMethods;
        IncludeProperties = includeProperties;
    }

    public string? Name { get; set; }
    public bool IncludeMethods { get; set; } = true;
    public bool IncludeProperties { get; set; } = true;
    public bool ImplementOnPartial { get; set; } = true;
}