using System.Diagnostics.CodeAnalysis;

namespace Roozie.AutoInterface.Definitions;

[SuppressMessage("StyleCop.CSharp.OrderingRules", "SA1201:Elements should appear in the correct order",
    Justification = "Shared/Utility class")]
internal static class Shared
{
    internal const string Namespace = $"{nameof(Roozie)}.{nameof(AutoInterface)}";

    internal static class FullNames
    {
        public const string AutoInterfaceAttribute = $"{Namespace}.{nameof(AutoInterfaceAttribute)}";
        public const string AddToInterfaceAttribute = $"{Namespace}.{nameof(AddToInterfaceAttribute)}";
    }

    internal static string GetGeneratedFileComment(string version) => $$"""
// <auto-generated>
// This file was generated by {{Namespace}} v{{version}}
// </auto-generated>
""";
}
