namespace Roozie.AutoInterface.Definitions;

internal static class Shared
{
    public const string Namespace = $"{nameof(Roozie)}.{nameof(AutoInterface)}";

    internal static class FullNames
    {
        public const string AutoInterfaceAttribute = $"{Namespace}.{nameof(AutoInterfaceAttribute)}";
        public const string AddToInterfaceAttribute = $"{Namespace}.{nameof(AddToInterfaceAttribute)}";
    }

    public static string GetGeneratedFileComment(string version) => $$"""
// <auto-generated>
// This file was generated by {{Namespace}} v{{version}}
// </auto-generated>
""";
}
