//HintName: IIndexers.g.cs
// <auto-generated>
// This file was generated by Roozie.AutoInterface v0.3.0-beta
// </auto-generated>
using Roozie.AutoInterface;
namespace Roozie.AutoInterface.Tests;
#nullable enable

public partial interface IIndexers
{
    int this[int index] {get;set;}

    int this[string v1] {get;set;}

    int this[string v1, int v2] {get;set;}
}
