//HintName: AddToInterfaceAttribute.g.cs
// This file was generated by Roozie.AutoInterface v0.1.1-beta
using System;

namespace Roozie.AutoInterface;
#nullable enable

/// <summary>
/// Add this attribute to mark a member that should be added to the generated interface.
/// </summary>
[AttributeUsage(AttributeTargets.Method | AttributeTargets.Property, Inherited = false, AllowMultiple = false)]
internal sealed class AddToInterfaceAttribute : Attribute
{
}
