//HintName: IClassInheritance.g.cs
// This file was generated by Roozie.AutoInterface v0.1.1-beta
using Roozie.AutoInterface;
using System;
using System.Text;
namespace Roozie.AutoInterface.Tests;
#nullable enable

public partial interface IClassInheritance
{
    System.Guid? Property {get;set;}

    string? TestString {get;set;}

    string TestMethod2(string input);

    string? TestMethod();
}
