//HintName: IBaseClass.g.cs
// This file was generated by Roozie.AutoInterface v0.1.1-beta
using Roozie.AutoInterface;
using System;
using System.Text;
namespace Roozie.AutoInterface.Tests;
#nullable enable

public partial interface IBaseClass
{
    System.Guid? Property {get;set;}

    string TestMethod2(string input);
}
