name: CI

on:
  push:
    branches:
      - "main"
    paths-ignore:
      - "LICENSE"
  pull_request:
    branches:
      - "main"
    paths-ignore:
      - "LICENSE"
  workflow_dispatch:

env:
  DOTNET_NOLOGO: true

jobs:
  build:
    name: CI
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Setup .NET Core
        uses: actions/setup-dotnet@v3
        with:
          global-json-file: global.json

      - name: build
        run: dotnet build 'Roozie.AutoInterface.sln' -c Release

      - name: test
        run: dotnet test 'Roozie.AutoInterface.sln' -c Release --no-build

      - name: pack
        run: dotnet pack 'Roozie.AutoInterface.sln' -c Release --no-build

      - name: upload nuget
        uses: actions/upload-artifact@v3
        with:
          name: nuget
          if-no-files-found: error
          retention-days: 3
          path: 'artifacts/*.nupkg'